spring.application.name=secondhand-backend
server.port=8080




spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:sqlite:secondhand.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

cloudinary.cloud-name=iozk27ac
cloudinary.api-key=413282944439372
cloudinary.api-secret=Z6wUYWZS6bZudwfK7KnFWT9nJTs